// AUTO-GENERATED by scripts/generate-backgrounds.mjs — do not edit by hand.
// Ported from PatternCraft (https://github.com/megh-bari/pattern-craft).
import * as React from "react";

/** Every DecorativeBackground pattern id, in source order. */
export const decorativeBackgroundVariants = [
  "top-gradient-radial",
  "bottom-gradient-radial",
  "top-violet-radial",
  "bottom-violet-radial",
  "top-slate-radial",
  "bottom-slate-radial",
  "top-teal-glow",
  "bottom-teal-glow",
  "top-pink-glow",
  "bottom-pink-glow",
  "top-amber-glow",
  "bottom-amber-glow",
  "top-emerald-glow",
  "bottom-emerald-glow",
  "dark-horizon-glow",
  "crimson-depth",
  "emerald-void",
  "violet-abyss",
  "azure-depths",
  "orchid -depths",
  "dark-horizon-glow-top",
  "crimson-depth-top",
  "emerald-void-top",
  "violet-abyss-top",
  "azure-depths-top",
  "orchid-depths-top",
  "purple-radial-bloom-light",
  "purple-corner-less",
  "purple-corner-high",
  "blue-corner-glow",
  "green-corner-soft",
  "pink-corner-dream",
  "orange-corner-warm",
  "teal-corner-cool",
  "yellow-corner-bright",
  "indigo-corner-deep",
  "rose-corner-elegant",
  "violet-dream-sphere",
  "lavender-cosmic-glow",
  "purple-haze-burst",
  "mystic-purple-orb",
  "soft-rose-glow-right-corner",
  "soft-rose-glow-left-corner",
  "soft-rose-glow-corners",
] as const;

export type DecorativeBackgroundVariant =
  (typeof decorativeBackgroundVariants)[number];

const variantStyles: Record<DecorativeBackgroundVariant, React.CSSProperties> =
  {
    "top-gradient-radial": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #fff 40%, #6366f1 100%)",
    },
    "bottom-gradient-radial": {
      background:
        "radial-gradient(125% 125% at 50% 90%, #fff 40%, #6366f1 100%)",
    },
    "top-violet-radial": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #fff 40%, #7c3aed 100%)",
    },
    "bottom-violet-radial": {
      background:
        "radial-gradient(125% 125% at 50% 90%, #fff 40%, #7c3aed 100%)",
    },
    "top-slate-radial": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #fff 40%, #475569 100%)",
    },
    "bottom-slate-radial": {
      background:
        "radial-gradient(125% 125% at 50% 90%, #fff 40%, #475569 100%)",
    },
    "top-teal-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 10%, #ffffff 40%, #14b8a6 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "bottom-teal-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 90%, #ffffff 40%, #14b8a6 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "top-pink-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 10%, #ffffff 40%, #ec4899 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "bottom-pink-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 90%, #ffffff 40%, #ec4899 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "top-amber-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 10%, #ffffff 40%, #f59e0b 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "bottom-amber-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 90%, #ffffff 40%, #f59e0b 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "top-emerald-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 10%, #ffffff 40%, #10b981 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "bottom-emerald-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(125% 125% at 50% 90%, #ffffff 40%, #10b981 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "dark-horizon-glow": {
      background: "#000000",
      backgroundImage:
        "\n     radial-gradient(125% 125% at 50% 90%, #000000 40%, #0d1a36 100%)\n    ",
      backgroundSize: "100% 100%",
    },
    "crimson-depth": {
      background: "#000000",
      backgroundImage:
        "radial-gradient(125% 125% at 50% 100%, #000000 40%, #2b0707 100%)",
      backgroundSize: "100% 100%",
    },
    "emerald-void": {
      background: "#000000",
      backgroundImage:
        "radial-gradient(125% 125% at 50% 90%, #000000 40%, #072607 100%)",
      backgroundSize: "100% 100%",
    },
    "violet-abyss": {
      background: "#000000",
      backgroundImage:
        "radial-gradient(125% 125% at 50% 90%, #000000 40%, #2b092b 100%)",
      backgroundSize: "100% 100%",
    },
    "azure-depths": {
      background: "#000000",
      backgroundImage:
        "radial-gradient(125% 125% at 50% 100%, #000000 40%, #010133 100%)",
      backgroundSize: "100% 100%",
    },
    "orchid -depths": {
      background: "#000000",
      backgroundImage:
        "radial-gradient(125% 125% at 50% 100%, #000000 40%, #350136 100%)",
      backgroundSize: "100% 100%",
    },
    "dark-horizon-glow-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #0d1a36 100%)",
    },
    "crimson-depth-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #2b0707 100%)",
    },
    "emerald-void-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #072607 100%)",
    },
    "violet-abyss-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #2b092b 100%)",
    },
    "azure-depths-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #010133 100%)",
    },
    "orchid-depths-top": {
      background:
        "radial-gradient(125% 125% at 50% 10%, #000000 40%, #350136 100%)",
    },
    "purple-radial-bloom-light": {
      background:
        "radial-gradient(circle at center, #F3E8FF 0%, #DDD6FE 30%, #C4B5FD 60%, #A78BFA 100%)",
    },
    "purple-corner-less": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #d5c5ff, transparent),\n      radial-gradient(circle 600px at 100% 200px, #d5c5ff, transparent)\n    ",
    },
    "purple-corner-high": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #a99bf7, transparent),\n      radial-gradient(circle 600px at 100% 200px, #a99bf7, transparent)\n    ",
    },
    "blue-corner-glow": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #bfdbfe, transparent),\n      radial-gradient(circle 600px at 100% 200px, #bfdbfe, transparent)\n    ",
    },
    "green-corner-soft": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #bbf7d0, transparent),\n      radial-gradient(circle 600px at 100% 200px, #bbf7d0, transparent)\n    ",
    },
    "pink-corner-dream": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #fce7f3, transparent),\n      radial-gradient(circle 600px at 100% 200px, #fce7f3, transparent)\n    ",
    },
    "orange-corner-warm": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #fed7aa, transparent),\n      radial-gradient(circle 600px at 100% 200px, #fed7aa, transparent)\n    ",
    },
    "teal-corner-cool": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #a7f3d0, transparent),\n      radial-gradient(circle 600px at 100% 200px, #a7f3d0, transparent)\n    ",
    },
    "yellow-corner-bright": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #fef3c7, transparent),\n      radial-gradient(circle 600px at 100% 200px, #fef3c7, transparent)\n    ",
    },
    "indigo-corner-deep": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #c7d2fe, transparent),\n      radial-gradient(circle 600px at 100% 200px, #c7d2fe, transparent)\n    ",
    },
    "rose-corner-elegant": {
      background: "#ffffff",
      backgroundImage:
        "\n      radial-gradient(circle 600px at 0% 200px, #fda4af, transparent),\n      radial-gradient(circle 600px at 100% 200px, #fda4af, transparent)\n    ",
    },
    "violet-dream-sphere": {
      background:
        "radial-gradient(ellipse at center, #DDD6FE 0%, #C4B5FD 25%, #A78BFA 50%, #8B5CF6 75%, #7C3AED 100%)",
    },
    "lavender-cosmic-glow": {
      background:
        "radial-gradient(circle at 40% 40%, #E9D5FF 0%, #C4B5FD 20%, #A78BFA 40%, #8B5CF6 60%, #6D28D9 80%, #581C87 100%)",
    },
    "purple-haze-burst": {
      background:
        "radial-gradient(circle at 30% 60%, #F3E8FF 0%, #DDD6FE 15%, #C4B5FD 30%, #A78BFA 45%, #8B5CF6 60%, #7C3AED 75%, #5B21B6 90%, #4C1D95 100%)",
    },
    "mystic-purple-orb": {
      background:
        "radial-gradient(circle at 50% 30%, #E9D5FF 0%, #C4B5FD 25%, #A78BFA 50%, #7C3AED 75%, #5B21B6 100%)",
    },
    "soft-rose-glow-right-corner": {
      background: "#fff8fc",
      backgroundImage:
        "\n      radial-gradient(circle 850px at 90% 90%, #f984e5, transparent)\n    ",
    },
    "soft-rose-glow-left-corner": {
      background: "#fff8fc",
      backgroundImage:
        "\n      radial-gradient(circle 850px at 10% 10%, #f984e5, transparent)\n    ",
    },
    "soft-rose-glow-corners": {
      background: "#fff8fc",
      backgroundImage:
        "\n      radial-gradient(circle 850px at 10% 10%, #f984e5, transparent),\n      radial-gradient(circle 850px at 90% 90%, #f984e5, transparent)\n    ",
    },
  };

export type DecorativeBackgroundProps = React.HTMLAttributes<HTMLDivElement> & {
  /** Background pattern to render. */
  variant?: DecorativeBackgroundVariant;
};

/**
 * Full-bleed decorative background. Drop it as the first child of a `relative`
 * container; your content sits above it at `z-raised` or higher.
 */
const DecorativeBackground = React.forwardRef<
  HTMLDivElement,
  DecorativeBackgroundProps
>(({ variant = "top-gradient-radial", className, style, ...props }, ref) => (
  <div
    ref={ref}
    data-slot="decorative-background"
    aria-hidden="true"
    className={`absolute inset-0 z-base ${className ?? ""}`}
    style={{ ...variantStyles[variant], ...style }}
    {...props}
  />
));
DecorativeBackground.displayName = "DecorativeBackground";

export { DecorativeBackground };
