// AUTO-GENERATED by scripts/generate-backgrounds.mjs — do not edit by hand.
// Ported from PatternCraft (https://github.com/megh-bari/pattern-craft).

/** Every GeometricBackground pattern id, in source order. */
export const geometricBackgroundVariants = [
  "purple-gradient-grid-right",
  "purple-gradient-grid-left",
  "dual-gradient-overlay-strong",
  "dual-gradient-overlay-strong-swapped",
  "dual-gradient-overlay-top",
  "dual-gradient-overlay-bottom",
  "purple-corner-grid",
  "grid-dual-purple-glow",
  "grid-quad-purple-glow",
  "top-fade-grid",
  "bottom-fade-grid",
  "diagonal-fade-grid-left",
  "diagonal-fade-grid-right",
  "diagonal-fade-bottom-grid-Left",
  "diagonal-fade-bottom-grid-right",
  "diagonal-fade-center-grid",
  "diagonal-cross-grid",
  "diagonal-cross-grid-top",
  "diagonal-cross-grid-bottom",
  "diagonal-cross-top-right-fade-grid",
  "diagonal-cross-top-left-fade-grid",
  "diagonal-cross-Bottom-right-fade-grid",
  "diagonal-cross-Bottom-left-fade-grid",
  "diagonal-cross-center-fade-grid",
  "dashed-grid-light",
  "dashed-top-fade-grid",
  "dashed-bottom-fade-grid",
  "dashed-top-left-fade-grid",
  "dashed-top-right-fade-grid",
  "dashed-bottom-right-fade-grid",
  "dashed-bottom-left-fade-grid",
  "dashed-center-fade-grid",
  "left-masked-basic-grid",
  "right-masked-basic-grid",
  "left-masked-diagonal-cross-grid",
  "right-masked-diagonal-cross-grid",
  "left-masked-dashed-grid-light",
  "right-masked-dashed-grid-light",
  "left-masked-concentric-squares-light",
  "right-masked-concentric-squares-light",
  "left-masked-circuit-board-light",
  "right-masked-circuit-board-light",
  "left-masked-circuit-board",
  "right-masked-circuit-board",
  "left-masked-white-grid-with-dots",
  "right-masked-white-grid-with-dots",
  "left-masked-noise-texture-darker-dots",
  "right-masked-noise-texture-darker-dots",
  "paper-texture",
  "diagonal-lines",
  "diagonal-light",
  "diagonal-light-green",
  "zigzag-lightning-light",
  "circuit-board-light",
  "concentric-squares-light",
  "woven-fabric-light",
  "crosshatch-art-light",
  "white-grid-with-dots",
  "noise-texture-darker-dots",
  "circuit-board",
  "basic-grid",
  "white-sphere-grid",
  "magenta-orb-grid-light",
  "dark-sphere-grid",
  "magenta-orb-grid",
  "dark-basic-grid-slate",
  "dark-basic-grid-faded",
  "black-basic-grid",
  "vercel-grid-subtle",
  "dark-grid-lines",
  "pixel-grid-pattern",
  "neon-vertical-lines",
  "dark-dot-matrix",
  "small-grid",
  "black-grid-white-dots",
  "dark-grid-white-dots",
  "dark-dotted-grid",
  "dark-white-dotted-grid",
  "dark-noise-colored-high",
  "matrix-green",
  "diagonal-green-glow",
  "diagonal-red/blue-glow",
  "diagonal-electric erange",
  "complex-multiplier",
  "hexagonal-lines",
  "diagonal-synthwave",
  "gradient-left-diagonal-lines",
  "gradient-right-diagonal-lines",
  "cross-diagonal-lines",
  "multi-cross-diagonal-lines",
  "variable-spacing",
  "circuit-board-vibes",
  "zigzag-lightning-dark",
  "circuit-board-dark",
  "dark-circuit-board",
  "concentric-squares-dark",
  "crosshatch-art-dark",
  "striped-dark",
  "diagonal-striped-grid",
] as const;

export type GeometricBackgroundVariant =
  (typeof geometricBackgroundVariants)[number];

/** Raw CSS values for each GeometricBackground variant. */
export const geometricBackgroundPresets: Record<
  GeometricBackgroundVariant,
  { background?: string; backgroundImage?: string; backgroundSize?: string }
> = {
  "purple-gradient-grid-right": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, #f0f0f0 1px, transparent 1px),\n      linear-gradient(to bottom, #f0f0f0 1px, transparent 1px),\n      radial-gradient(circle 800px at 100% 200px, #d5c5ff, transparent)\n    ",
    backgroundSize: "96px 64px, 96px 64px, 100% 100%",
  },
  "purple-gradient-grid-left": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, #f0f0f0 1px, transparent 1px),\n      linear-gradient(to bottom, #f0f0f0 1px, transparent 1px),\n      radial-gradient(circle 800px at 0% 200px, #d5c5ff, transparent)\n    ",
    backgroundSize: "96px 64px, 96px 64px, 100% 100%",
  },
  "dual-gradient-overlay-strong": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(229,231,235,0.8) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(229,231,235,0.8) 1px, transparent 1px),\n      radial-gradient(circle 500px at 20% 80%, rgba(139,92,246,0.3), transparent),\n      radial-gradient(circle 500px at 80% 20%, rgba(59,130,246,0.3), transparent)\n    ",
    backgroundSize: "48px 48px, 48px 48px, 100% 100%, 100% 100%",
  },
  "dual-gradient-overlay-strong-swapped": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(229,231,235,0.8) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(229,231,235,0.8) 1px, transparent 1px),\n      radial-gradient(circle 500px at 20% 20%, rgba(139,92,246,0.3), transparent),\n      radial-gradient(circle 500px at 80% 80%, rgba(59,130,246,0.3), transparent)\n    ",
    backgroundSize: "48px 48px, 48px 48px, 100% 100%, 100% 100%",
  },
  "dual-gradient-overlay-top": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(229,231,235,0.8) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(229,231,235,0.8) 1px, transparent 1px),\n      radial-gradient(circle 500px at 0% 20%, rgba(139,92,246,0.3), transparent),\n      radial-gradient(circle 500px at 100% 0%, rgba(59,130,246,0.3), transparent)\n    ",
    backgroundSize: "48px 48px, 48px 48px, 100% 100%, 100% 100%",
  },
  "dual-gradient-overlay-bottom": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(229,231,235,0.8) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(229,231,235,0.8) 1px, transparent 1px),\n      radial-gradient(circle 500px at 20% 100%, rgba(139,92,246,0.3), transparent),\n      radial-gradient(circle 500px at 100% 80%, rgba(59,130,246,0.3), transparent)\n    ",
    backgroundSize: "48px 48px, 48px 48px, 100% 100%, 100% 100%",
  },
  "purple-corner-grid": {
    background: "#ffffff",
    backgroundImage:
      "\n     linear-gradient(to right, #f0f0f0 1px, transparent 1px),\n     linear-gradient(to bottom, #f0f0f0 1px, transparent 1px),\n     radial-gradient(circle 600px at 0% 200px, #d5c5ff, transparent),\n     radial-gradient(circle 600px at 100% 200px, #d5c5ff, transparent)\n   ",
    backgroundSize: "20px 20px, 20px 20px, 100% 100%, 100% 100%",
  },
  "grid-dual-purple-glow": {
    background: "#ffffff",
    backgroundImage:
      "\n     linear-gradient(to right, #f0f0f0 1px, transparent 1px),\n     linear-gradient(to bottom, #f0f0f0 1px, transparent 1px),\n     radial-gradient(circle 600px at 0% 200px, #d5c5ff, transparent),\n     radial-gradient(circle 600px at 100% 200px, #d5c5ff, transparent)\n   ",
    backgroundSize:
      "\n     96px 64px,    \n     96px 64px,    \n     100% 100%,    \n     100% 100%  \n   ",
  },
  "grid-quad-purple-glow": {
    background: "#ffffff",
    backgroundImage:
      "\n     linear-gradient(to right, #f0f0f0 1px, transparent 1px),\n     linear-gradient(to bottom, #f0f0f0 1px, transparent 1px),\n     radial-gradient(circle 600px at 0% 200px, #d5c5ff, transparent),     /* Left */\n     radial-gradient(circle 600px at 100% 200px, #d5c5ff, transparent),  /* Right */\n     radial-gradient(circle 600px at 50% 0px, #d5c5ff, transparent),     /* Top */\n     radial-gradient(circle 600px at 50% 100%, #d5c5ff, transparent)     /* Bottom */\n   ",
    backgroundSize:
      "\n     96px 64px,    \n     96px 64px,    \n     100% 100%,    \n     100% 100%,\n     100% 100%,\n     100% 100%\n   ",
  },
  "top-fade-grid": {
    background: "#f8fafc",
    backgroundImage:
      "\n      linear-gradient(to right, #e2e8f0 1px, transparent 1px),\n      linear-gradient(to bottom, #e2e8f0 1px, transparent 1px)\n    ",
    backgroundSize: "20px 30px",
  },
  "bottom-fade-grid": {
    background: "#f8fafc",
    backgroundImage:
      "\n        linear-gradient(to right, #e2e8f0 1px, transparent 1px),\n        linear-gradient(to bottom, #e2e8f0 1px, transparent 1px)\n      ",
    backgroundSize: "20px 30px",
  },
  "diagonal-fade-grid-left": {
    background: "#f9fafb",
    backgroundImage:
      "\n        linear-gradient(to right, #d1d5db 1px, transparent 1px),\n        linear-gradient(to bottom, #d1d5db 1px, transparent 1px)\n      ",
    backgroundSize: "32px 32px",
  },
  "diagonal-fade-grid-right": {
    background: "#f9fafb",
    backgroundImage:
      "\n      linear-gradient(to right, #d1d5db 1px, transparent 1px),\n      linear-gradient(to bottom, #d1d5db 1px, transparent 1px)\n    ",
    backgroundSize: "32px 32px",
  },
  "diagonal-fade-bottom-grid-Left": {
    background: "#f9fafb",
    backgroundImage:
      "\n      linear-gradient(to right, #d1d5db 1px, transparent 1px),\n      linear-gradient(to bottom, #d1d5db 1px, transparent 1px)\n    ",
    backgroundSize: "32px 32px",
  },
  "diagonal-fade-bottom-grid-right": {
    background: "#f9fafb",
    backgroundImage:
      "\n      linear-gradient(to right, #d1d5db 1px, transparent 1px),\n      linear-gradient(to bottom, #d1d5db 1px, transparent 1px)\n    ",
    backgroundSize: "32px 32px",
  },
  "diagonal-fade-center-grid": {
    background: "#f9fafb",
    backgroundImage:
      "\n      linear-gradient(to right, #d1d5db 1px, transparent 1px),\n      linear-gradient(to bottom, #d1d5db 1px, transparent 1px)\n    ",
    backgroundSize: "32px 32px",
  },
  "diagonal-cross-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-grid-top": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-grid-bottom": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-top-right-fade-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-top-left-fade-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-Bottom-right-fade-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-Bottom-left-fade-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-cross-center-fade-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "dashed-grid-light": {
    backgroundImage:
      "\n        linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n      ",
    backgroundSize: "20px 20px",
  },
  "dashed-top-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-bottom-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-top-left-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-top-right-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-bottom-right-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-bottom-left-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "dashed-center-fade-grid": {
    backgroundImage:
      "\n             linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n          ",
    backgroundSize: "20px 20px",
  },
  "left-masked-basic-grid": {
    backgroundImage:
      "\n        linear-gradient(to right, #e5e7eb 1px, transparent 1px),\n        linear-gradient(to bottom, #e5e7eb 1px, transparent 1px)\n      ",
    backgroundSize: "40px 40px",
  },
  "right-masked-basic-grid": {
    backgroundImage:
      "\n        linear-gradient(to right, #e5e7eb 1px, transparent 1px),\n        linear-gradient(to bottom, #e5e7eb 1px, transparent 1px)\n      ",
    backgroundSize: "40px 40px",
  },
  "left-masked-diagonal-cross-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "right-masked-diagonal-cross-grid": {
    background: "white",
    backgroundImage:
      "\n      linear-gradient(45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%),\n      linear-gradient(-45deg, transparent 49%, #e5e7eb 49%, #e5e7eb 51%, transparent 51%)\n    ",
    backgroundSize: "40px 40px",
  },
  "left-masked-dashed-grid-light": {
    backgroundImage:
      "\n        linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n      ",
    backgroundSize: "20px 20px",
  },
  "right-masked-dashed-grid-light": {
    backgroundImage:
      "\n        linear-gradient(to right, #e7e5e4 1px, transparent 1px),\n        linear-gradient(to bottom, #e7e5e4 1px, transparent 1px)\n      ",
    backgroundSize: "20px 20px",
  },
  "left-masked-concentric-squares-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(90deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px),\n      repeating-linear-gradient(90deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px)\n    ",
  },
  "right-masked-concentric-squares-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(90deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px),\n      repeating-linear-gradient(90deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px)\n    ",
  },
  "left-masked-circuit-board-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      repeating-linear-gradient(90deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      radial-gradient(circle at 20px 20px, rgba(55, 65, 81, 0.12) 2px, transparent 2px),\n      radial-gradient(circle at 40px 40px, rgba(55, 65, 81, 0.12) 2px, transparent 2px)\n    ",
    backgroundSize: "40px 40px, 40px 40px, 40px 40px, 40px 40px",
  },
  "right-masked-circuit-board-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      repeating-linear-gradient(90deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      radial-gradient(circle at 20px 20px, rgba(55, 65, 81, 0.12) 2px, transparent 2px),\n      radial-gradient(circle at 40px 40px, rgba(55, 65, 81, 0.12) 2px, transparent 2px)\n    ",
    backgroundSize: "40px 40px, 40px 40px, 40px 40px, 40px 40px",
  },
  "left-masked-circuit-board": {
    background: "#f8fafc",
    backgroundImage:
      "\n        linear-gradient(90deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(180deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(90deg, #cbd5e1 1px, transparent 1px),\n        linear-gradient(180deg, #cbd5e1 1px, transparent 1px)\n      ",
    backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
  },
  "right-masked-circuit-board": {
    background: "#f8fafc",
    backgroundImage:
      "\n        linear-gradient(90deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(180deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(90deg, #cbd5e1 1px, transparent 1px),\n        linear-gradient(180deg, #cbd5e1 1px, transparent 1px)\n      ",
    backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
  },
  "left-masked-white-grid-with-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(0,0,0,0.06) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(0,0,0,0.06) 1px, transparent 1px),\n      radial-gradient(circle, rgba(51,65,85,0.4) 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px, 20px 20px, 20px 20px",
  },
  "right-masked-white-grid-with-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(0,0,0,0.06) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(0,0,0,0.06) 1px, transparent 1px),\n      radial-gradient(circle, rgba(51,65,85,0.4) 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px, 20px 20px, 20px 20px",
  },
  "left-masked-noise-texture-darker-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      radial-gradient(circle at 1px 1px, rgba(0, 0, 0, 0.35) 1px, transparent 0)\n    ",
    backgroundSize: "20px 20px",
  },
  "right-masked-noise-texture-darker-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      radial-gradient(circle at 1px 1px, rgba(0, 0, 0, 0.35) 1px, transparent 0)\n    ",
    backgroundSize: "20px 20px",
  },
  "paper-texture": {
    background: "#faf9f6",
    backgroundImage:
      "\n        radial-gradient(circle at 1px 1px, rgba(0,0,0,0.08) 1px, transparent 0),\n        repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.02) 2px, rgba(0,0,0,0.02) 4px),\n        repeating-linear-gradient(90deg, transparent, transparent 2px, rgba(0,0,0,0.02) 2px, rgba(0,0,0,0.02) 4px)\n      ",
    backgroundSize: "8px 8px, 32px 32px, 32px 32px",
  },
  "diagonal-lines": {
    backgroundImage:
      "repeating-linear-gradient(45deg, transparent, transparent 2px, #f3f4f6 2px, #f3f4f6 4px)",
  },
  "diagonal-light": {
    background: "#fafafa",
    backgroundImage:
      "\n       repeating-linear-gradient(45deg, rgba(0, 0, 0, 0.1) 0, rgba(0, 0, 0, 0.1) 1px, transparent 1px, transparent 20px),\n        repeating-linear-gradient(-45deg, rgba(0, 0, 0, 0.1) 0, rgba(0, 0, 0, 0.1) 1px, transparent 1px, transparent 20px)\n      ",
    backgroundSize: "40px 40px",
  },
  "diagonal-light-green": {
    background: "#fafafa",
    backgroundImage:
      "\n       repeating-linear-gradient(45deg, rgba(255, 0, 100, 0.1) 0, rgba(255, 0, 100, 0.1) 1px, transparent 1px, transparent 20px),\n        repeating-linear-gradient(-45deg, rgba(255, 0, 100, 0.1) 0, rgba(255, 0, 100, 0.1) 1px, transparent 1px, transparent 20px)\n      ",
    backgroundSize: "40px 40px",
  },
  "zigzag-lightning-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 20px, rgba(75, 85, 99, 0.08) 20px, rgba(75, 85, 99, 0.08) 21px),\n      repeating-linear-gradient(90deg, transparent, transparent 30px, rgba(107, 114, 128, 0.06) 30px, rgba(107, 114, 128, 0.06) 31px),\n      repeating-linear-gradient(60deg, transparent, transparent 40px, rgba(55, 65, 81, 0.05) 40px, rgba(55, 65, 81, 0.05) 41px),\n      repeating-linear-gradient(150deg, transparent, transparent 35px, rgba(31, 41, 55, 0.04) 35px, rgba(31, 41, 55, 0.04) 36px)\n    ",
  },
  "circuit-board-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      repeating-linear-gradient(90deg, transparent, transparent 19px, rgba(75, 85, 99, 0.08) 19px, rgba(75, 85, 99, 0.08) 20px, transparent 20px, transparent 39px, rgba(75, 85, 99, 0.08) 39px, rgba(75, 85, 99, 0.08) 40px),\n      radial-gradient(circle at 20px 20px, rgba(55, 65, 81, 0.12) 2px, transparent 2px),\n      radial-gradient(circle at 40px 40px, rgba(55, 65, 81, 0.12) 2px, transparent 2px)\n    ",
    backgroundSize: "40px 40px, 40px 40px, 40px 40px, 40px 40px",
  },
  "concentric-squares-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(90deg, transparent, transparent 5px, rgba(75, 85, 99, 0.06) 5px, rgba(75, 85, 99, 0.06) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px),\n      repeating-linear-gradient(90deg, transparent, transparent 10px, rgba(107, 114, 128, 0.04) 10px, rgba(107, 114, 128, 0.04) 11px, transparent 11px, transparent 30px)\n    ",
  },
  "woven-fabric-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, rgba(75, 85, 99, 0.08), rgba(75, 85, 99, 0.08) 2px, transparent 2px, transparent 6px),\n      repeating-linear-gradient(90deg, rgba(107, 114, 128, 0.06), rgba(107, 114, 128, 0.06) 2px, transparent 2px, transparent 6px),\n      repeating-linear-gradient(0deg, rgba(55, 65, 81, 0.04), rgba(55, 65, 81, 0.04) 1px, transparent 1px, transparent 12px),\n      repeating-linear-gradient(90deg, rgba(55, 65, 81, 0.04), rgba(55, 65, 81, 0.04) 1px, transparent 1px, transparent 12px)\n    ",
  },
  "crosshatch-art-light": {
    background: "#ffffff",
    backgroundImage:
      "\n      repeating-linear-gradient(22.5deg, transparent, transparent 2px, rgba(75, 85, 99, 0.06) 2px, rgba(75, 85, 99, 0.06) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(67.5deg, transparent, transparent 2px, rgba(107, 114, 128, 0.05) 2px, rgba(107, 114, 128, 0.05) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(112.5deg, transparent, transparent 2px, rgba(55, 65, 81, 0.04) 2px, rgba(55, 65, 81, 0.04) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(157.5deg, transparent, transparent 2px, rgba(31, 41, 55, 0.03) 2px, rgba(31, 41, 55, 0.03) 3px, transparent 3px, transparent 8px)\n    ",
  },
  "white-grid-with-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(0,0,0,0.06) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(0,0,0,0.06) 1px, transparent 1px),\n      radial-gradient(circle, rgba(51,65,85,0.4) 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px, 20px 20px, 20px 20px",
  },
  "noise-texture-darker-dots": {
    background: "#ffffff",
    backgroundImage:
      "\n      radial-gradient(circle at 1px 1px, rgba(0, 0, 0, 0.35) 1px, transparent 0)\n    ",
    backgroundSize: "20px 20px",
  },
  "circuit-board": {
    background: "#f8fafc",
    backgroundImage:
      "\n        linear-gradient(90deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(180deg, #e2e8f0 1px, transparent 1px),\n        linear-gradient(90deg, #cbd5e1 1px, transparent 1px),\n        linear-gradient(180deg, #cbd5e1 1px, transparent 1px)\n      ",
    backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
  },
  "basic-grid": {
    backgroundImage:
      "\n        linear-gradient(to right, #e5e7eb 1px, transparent 1px),\n        linear-gradient(to bottom, #e5e7eb 1px, transparent 1px)\n      ",
    backgroundSize: "40px 40px",
  },
  "white-sphere-grid": {
    background: "white",
    backgroundImage:
      "\n     linear-gradient(to right, rgba(71,85,105,0.3) 1px, transparent 1px),\n     linear-gradient(to bottom, rgba(71,85,105,0.3) 1px, transparent 1px),\n     radial-gradient(circle at 50% 50%, rgba(139,92,246,0.25) 0%, rgba(139,92,246,0.1) 40%, transparent 80%)\n   ",
    backgroundSize: "32px 32px, 32px 32px, 100% 100%",
  },
  "magenta-orb-grid-light": {
    background: "white",
    backgroundImage:
      "\n   linear-gradient(to right, rgba(71,85,105,0.15) 1px, transparent 1px),\n   linear-gradient(to bottom, rgba(71,85,105,0.15) 1px, transparent 1px),\n   radial-gradient(circle at 50% 60%, rgba(236,72,153,0.15) 0%, rgba(168,85,247,0.05) 40%, transparent 70%)\n ",
    backgroundSize: "40px 40px, 40px 40px, 100% 100%",
  },
  "dark-sphere-grid": {
    background: "#020617",
    backgroundImage:
      "\n        linear-gradient(to right, rgba(71,85,105,0.3) 1px, transparent 1px),\n        linear-gradient(to bottom, rgba(71,85,105,0.3) 1px, transparent 1px),\n        radial-gradient(circle at 50% 50%, rgba(139,92,246,0.15) 0%, transparent 70%)\n      ",
    backgroundSize: "32px 32px, 32px 32px, 100% 100%",
  },
  "magenta-orb-grid": {
    background: "#020617",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(71,85,105,0.15) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(71,85,105,0.15) 1px, transparent 1px),\n      radial-gradient(circle at 50% 60%, rgba(236,72,153,0.15) 0%, rgba(168,85,247,0.05) 40%, transparent 70%)\n    ",
    backgroundSize: "40px 40px, 40px 40px, 100% 100%",
  },
  "dark-basic-grid-slate": {
    background: "#020617",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(100,116,139,0.4) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(100,116,139,0.4) 1px, transparent 1px)\n    ",
    backgroundSize: "40px 40px",
  },
  "dark-basic-grid-faded": {
    background: "#0f172a",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(148,163,184,0.2) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(148,163,184,0.2) 1px, transparent 1px)\n    ",
    backgroundSize: "40px 40px",
  },
  "black-basic-grid": {
    background: "#000000",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(75, 85, 99, 0.4) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(75, 85, 99, 0.4) 1px, transparent 1px)\n    ",
    backgroundSize: "40px 40px",
  },
  "vercel-grid-subtle": {
    background: "#000000",
    backgroundImage:
      "\n      linear-gradient(rgba(255, 255, 255, 0.1) 1px, transparent 1px),\n      linear-gradient(90deg, rgba(255, 255, 255, 0.1) 1px, transparent 1px)\n    ",
    backgroundSize: "60px 60px",
  },
  "dark-grid-lines": {
    background: "#000000",
    backgroundImage:
      "\n     linear-gradient(to right, #262626 1px, transparent 1px),\n     linear-gradient(to bottom, #262626 1px, transparent 1px)\n   ",
    backgroundSize: "20px 20px",
  },
  "pixel-grid-pattern": {
    backgroundImage:
      "\n     linear-gradient(#333333 1px, transparent 1px),\n     linear-gradient(90deg, #333333 1px, transparent 1px)\n   ",
    backgroundSize: "8px 8px",
  },
  "neon-vertical-lines": {
    background: "#000000",
    backgroundImage:
      "\n       repeating-linear-gradient(\n                          90deg,\n                          transparent 0px,\n                          transparent 79px,\n                          rgba(255, 255, 255, 0.05) 80px,\n                          rgba(255, 255, 255, 0.05) 81px\n                        )\n    ",
    backgroundSize: "100% 100%",
  },
  "dark-dot-matrix": {
    backgroundImage:
      "\n     radial-gradient(circle at 25% 25%, #222222 0.5px, transparent 1px),\n     radial-gradient(circle at 75% 75%, #111111 0.5px, transparent 1px)\n   ",
    backgroundSize: "10px 10px",
  },
  "small-grid": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      linear-gradient(to right, #262626 1px, transparent 1px),\n      linear-gradient(to bottom, #262626 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px",
  },
  "black-grid-white-dots": {
    background: "#000000",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(255,255,255,0.06) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(255,255,255,0.06) 1px, transparent 1px),\n      radial-gradient(circle, rgba(255,255,255,0.6) 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px, 20px 20px, 20px 20px",
  },
  "dark-grid-white-dots": {
    background: "#0f172a",
    backgroundImage:
      "\n      linear-gradient(to right, rgba(255,255,255,0.06) 1px, transparent 1px),\n      linear-gradient(to bottom, rgba(255,255,255,0.06) 1px, transparent 1px),\n      radial-gradient(circle, rgba(255,255,255,0.6) 1px, transparent 1px)\n    ",
    backgroundSize: "20px 20px, 20px 20px, 20px 20px",
  },
  "dark-dotted-grid": {
    background: "#0f172a",
    backgroundImage:
      "\n        radial-gradient(circle, rgba(139,92,246,0.6) 1px, transparent 1px),\n        radial-gradient(circle, rgba(59,130,246,0.4) 1px, transparent 1px),\n        radial-gradient(circle, rgba(236,72,153,0.5) 1px, transparent 1px)\n      ",
    backgroundSize: "20px 20px, 40px 40px, 60px 60px",
  },
  "dark-white-dotted-grid": {
    background: "#000000",
    backgroundImage:
      "\n      radial-gradient(circle, rgba(255, 255, 255, 0.2) 1.5px, transparent 1.5px)\n    ",
    backgroundSize: "30px 30px",
  },
  "dark-noise-colored-high": {
    background: "#000000",
    backgroundImage:
      "\n      radial-gradient(circle at 1px 1px, rgba(139, 92, 246, 0.2) 1px, transparent 0),\n      radial-gradient(circle at 1px 1px, rgba(59, 130, 246, 0.18) 1px, transparent 0),\n      radial-gradient(circle at 1px 1px, rgba(236, 72, 153, 0.15) 1px, transparent 0)\n    ",
    backgroundSize: "20px 20px, 30px 30px, 25px 25px",
  },
  "matrix-green": {
    background: "#000000",
    backgroundImage:
      "\n       repeating-linear-gradient(45deg, rgba(0, 255, 65, 0.08) 0, rgba(0, 255, 65, 0.08) 1px, transparent 1px, transparent 12px),\n        repeating-linear-gradient(-45deg, rgba(0, 255, 65, 0.08) 0, rgba(0, 255, 65, 0.08) 1px, transparent 1px, transparent 12px),\n        repeating-linear-gradient(90deg, rgba(0, 255, 65, 0.03) 0, rgba(0, 255, 65, 0.03) 1px, transparent 1px, transparent 4px)\n    ",
    backgroundSize: "24px 24px, 24px 24px, 8px 8px",
  },
  "diagonal-green-glow": {
    background: "#0f0f0f",
    backgroundImage:
      "\n        repeating-linear-gradient(45deg, rgba(0, 255, 128, 0.1) 0, rgba(0, 255, 128, 0.1) 1px, transparent 1px, transparent 20px),\n        repeating-linear-gradient(-45deg, rgba(0, 255, 128, 0.1) 0, rgba(0, 255, 128, 0.1) 1px, transparent 1px, transparent 20px)\n      ",
    backgroundSize: "40px 40px",
  },
  "diagonal-red/blue-glow": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(45deg, rgba(255, 0, 100, 0.2) 0, rgba(255, 0, 100, 0.2) 1px, transparent 1px, transparent 20px),\n      repeating-linear-gradient(-45deg, rgba(0, 255, 200, 0.15) 0, rgba(0, 255, 200, 0.15) 1px, transparent 1px, transparent 20px)\n    ",
    backgroundSize: "40px 40px",
  },
  "diagonal-electric erange": {
    background: "#0f0f0f",
    backgroundImage:
      "\n     repeating-linear-gradient(45deg, rgba(255, 140, 0, 0.12) 0, rgba(255, 140, 0, 0.12) 1px, transparent 1px, transparent 22px),\n        repeating-linear-gradient(-45deg, rgba(255, 69, 0, 0.08) 0, rgba(255, 69, 0, 0.08) 1px, transparent 1px, transparent 22px)\n    ",
    backgroundSize: "44px 44px",
  },
  "complex-multiplier": {
    background: "#101014",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, rgba(255,255,255,0.04) 0, rgba(255,255,255,0.04) 1px, transparent 1px, transparent 40px),\n      repeating-linear-gradient(45deg, rgba(0,255,128,0.09) 0, rgba(0,255,128,0.09) 1px, transparent 1px, transparent 20px),\n     repeating-linear-gradient(-45deg, rgba(255,0,128,0.10) 0, rgba(255,0,128,0.10) 1px, transparent 1px, transparent 30px),\n      repeating-linear-gradient(90deg, rgba(255,255,255,0.03) 0, rgba(255,255,255,0.03) 1px, transparent 1px, transparent 80px),\n      radial-gradient(circle at 60% 40%, rgba(0,255,128,0.05) 0, transparent 60%)\n    ",
    backgroundSize: "80px 80px, 40px 40px, 60px 60px, 80px 80px, 100% 100%",
  },
  "hexagonal-lines": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(60deg, rgba(255, 0, 100, 0.2) 0, rgba(255, 0, 100, 0.2) 1px, transparent 1px, transparent 22px),\n      repeating-linear-gradient(-60deg, rgba(0, 255, 200, 0.15) 0, rgba(0, 255, 200, 0.15) 1px, transparent 1px, transparent 22px),\n      repeating-linear-gradient(0deg, rgba(255, 0, 100, 0.2) 0, rgba(255, 0, 100, 0.2) 1px, transparent 1px, transparent 22px)\n    ",
    backgroundSize: "44px 44px",
  },
  "diagonal-synthwave": {
    background: "#0a0a0a",
    backgroundImage:
      "\n          repeating-linear-gradient(45deg, rgba(255, 20, 147, 0.15) 0, rgba(255, 20, 147, 0.15) 2px, transparent 2px, transparent 30px),\n        repeating-linear-gradient(-45deg, rgba(0, 255, 255, 0.1) 0, rgba(0, 255, 255, 0.1) 1px, transparent 1px, transparent 25px)\n      ",
    backgroundSize: "40px 40px",
  },
  "gradient-left-diagonal-lines": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(45deg, \n        rgba(0, 255, 128, 0.2) 0px, \n        rgba(0, 255, 128, 0) 2px, \n        transparent 2px, \n        transparent 25px\n      )\n    ",
  },
  "gradient-right-diagonal-lines": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(-45deg, \n        rgba(255, 0, 100, 0.2) 0px, \n        rgba(255, 0, 100, 0) 2px, \n        transparent 2px, \n        transparent 25px\n      )\n    ",
  },
  "cross-diagonal-lines": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(45deg, rgba(0, 255, 128, 0.1) 0, rgba(0, 255, 128, 0.1) 1px, transparent 1px, transparent 20px),\n        repeating-linear-gradient(-45deg, rgba(0, 255, 128, 0.1) 0, rgba(0, 255, 128, 0.1) 1px, transparent 1px, transparent 20px)\n    ",
  },
  "multi-cross-diagonal-lines": {
    background: "#0f0f0f",
    backgroundImage:
      "\n       repeating-linear-gradient(-45deg, rgba(255, 0, 100, 0.2) 0, rgba(255, 0, 100, 0.2) 1px, transparent 1px, transparent 20px),\n        repeating-linear-gradient(45deg, rgba(0, 255, 128, 0.2) 0, rgba(0, 255, 128, 0.2) 1px, transparent 1px, transparent 20px)\n    ",
  },
  "variable-spacing": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(30deg, \n        rgba(255, 100, 0, 0.1) 0, \n        rgba(255, 100, 0, 0.1) 1px, \n        transparent 1px, \n        transparent 10px,\n        rgba(255, 100, 0, 0.15) 11px, \n        rgba(255, 100, 0, 0.15) 12px, \n        transparent 12px, \n        transparent 40px\n      )\n    ",
  },
  "circuit-board-vibes": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, \n        rgba(0, 255, 0, 0.12) 0, rgba(0, 255, 0, 0.12) 1px, \n        transparent 1px, transparent 40px\n      ),\n      repeating-linear-gradient(90deg, \n        rgba(0, 255, 0, 0.08) 0, rgba(0, 255, 0, 0.08) 1px, \n        transparent 1px, transparent 80px\n      ),\n      repeating-linear-gradient(45deg, \n        rgba(255, 100, 0, 0.10) 0, rgba(255, 100, 0, 0.10) 1px, \n        transparent 1px, transparent 160px\n      )\n    ",
    backgroundSize: "80px 80px, 160px 160px, 320px 320px",
  },
  "zigzag-lightning-dark": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 20px, rgba(34, 197, 94, 0.12) 20px, rgba(34, 197, 94, 0.12) 21px),\n      repeating-linear-gradient(90deg, transparent, transparent 30px, rgba(16, 185, 129, 0.10) 30px, rgba(16, 185, 129, 0.10) 31px),\n      repeating-linear-gradient(60deg, transparent, transparent 40px, rgba(59, 130, 246, 0.08) 40px, rgba(59, 130, 246, 0.08) 41px),\n      repeating-linear-gradient(150deg, transparent, transparent 35px, rgba(147, 51, 234, 0.06) 35px, rgba(147, 51, 234, 0.06) 36px)\n    ",
  },
  "circuit-board-dark": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 19px, rgba(34, 197, 94, 0.15) 19px, rgba(34, 197, 94, 0.15) 20px, transparent 20px, transparent 39px, rgba(34, 197, 94, 0.15) 39px, rgba(34, 197, 94, 0.15) 40px),\n      repeating-linear-gradient(90deg, transparent, transparent 19px, rgba(34, 197, 94, 0.15) 19px, rgba(34, 197, 94, 0.15) 20px, transparent 20px, transparent 39px, rgba(34, 197, 94, 0.15) 39px, rgba(34, 197, 94, 0.15) 40px),\n      radial-gradient(circle at 20px 20px, rgba(16, 185, 129, 0.18) 2px, transparent 2px),\n      radial-gradient(circle at 40px 40px, rgba(16, 185, 129, 0.18) 2px, transparent 2px)\n    ",
    backgroundSize: "40px 40px, 40px 40px, 40px 40px, 40px 40px",
  },
  "dark-circuit-board": {
    backgroundImage:
      "\n      linear-gradient(90deg, #171717 1px, transparent 1px),\n      linear-gradient(180deg, #171717 1px, transparent 1px),\n      linear-gradient(90deg, #262626 1px, transparent 1px),\n      linear-gradient(180deg, #262626 1px, transparent 1px)\n    ",
    backgroundSize: "50px 50px, 50px 50px, 10px 10px, 10px 10px",
  },
  "concentric-squares-dark": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(0deg, transparent, transparent 5px, rgba(99, 102, 241, 0.15) 5px, rgba(99, 102, 241, 0.15) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(90deg, transparent, transparent 5px, rgba(99, 102, 241, 0.15) 5px, rgba(99, 102, 241, 0.15) 6px, transparent 6px, transparent 15px),\n      repeating-linear-gradient(0deg, transparent, transparent 10px, rgba(139, 92, 246, 0.12) 10px, rgba(139, 92, 246, 0.12) 11px, transparent 11px, transparent 30px),\n      repeating-linear-gradient(90deg, transparent, transparent 10px, rgba(139, 92, 246, 0.12) 10px, rgba(139, 92, 246, 0.12) 11px, transparent 11px, transparent 30px)\n    ",
  },
  "crosshatch-art-dark": {
    background: "#0f0f0f",
    backgroundImage:
      "\n      repeating-linear-gradient(22.5deg, transparent, transparent 2px, rgba(16, 185, 129, 0.18) 2px, rgba(16, 185, 129, 0.18) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(67.5deg, transparent, transparent 2px, rgba(245, 101, 101, 0.10) 2px, rgba(245, 101, 101, 0.10) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(112.5deg, transparent, transparent 2px, rgba(234, 179, 8, 0.08) 2px, rgba(234, 179, 8, 0.08) 3px, transparent 3px, transparent 8px),\n      repeating-linear-gradient(157.5deg, transparent, transparent 2px, rgba(249, 115, 22, 0.06) 2px, rgba(249, 115, 22, 0.06) 3px, transparent 3px, transparent 8px)\n    ",
  },
  "striped-dark": {
    background:
      "repeating-linear-gradient(45deg, #000 0px, #111 2px, #000 4px, #222 6px)",
  },
  "diagonal-striped-grid": {
    background: "#ffffff",
    backgroundImage:
      "\n        linear-gradient(90deg, rgba(16,185,129,0.25) 1px, transparent 0),\n        linear-gradient(180deg, rgba(16,185,129,0.25) 1px, transparent 0),\n        repeating-linear-gradient(45deg, rgba(16,185,129,0.2) 0 2px, transparent 2px 6px)\n      ",
    backgroundSize: "24px 24px, 24px 24px, 24px 24px",
  },
};
